language: haskell

env:
  - GHCVER=7.8.2

before_install:
  # If $GHCVER is the one travis has, don't bother reinstalling it.
  # We can also have faster builds by installing some libraries with
  # `apt`. If it isn't, install the GHC we want from hvr's PPA along
  # with cabal-1.18.
  - |
    if [ $GHCVER = `ghc --numeric-version` ]; then
      # Try installing some of the build-deps with apt-get for speed.
      travis/cabal-apt-install --enable-tests $MODE
      export CABAL=cabal
    else
      # Install the GHC we want from hvr's PPA
      travis_retry sudo add-apt-repository -y ppa:hvr/ghc
      travis_retry sudo apt-get update
      travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
      export CABAL=cabal-1.18
      export PATH=/opt/ghc/$GHCVER/bin:$PATH
    fi
  - export PATH=$HOME/.cabal/bin:$PATH
  # Uncomment whenever hackage is down.
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && $CABAL update
  - $CABAL update

  # Update happy when building with GHC head
  - |
    if [ $GHCVER = "head" ] || [ $GHCVER = "7.8.2" ]; then
      $CABAL install happy alex
    fi
  - $CABAL install hlint packdeps packunused --constraint 'packunused >= 0.1.1.2'

install:
  - $CABAL install --dependencies-only --enable-tests $MODE
  - $CABAL configure -flib-Werror --enable-tests $MODE

script:
  - $CABAL build --ghc-options=-ddump-minimal-imports
  - $CABAL test --show-details=always
  - packdeps ermine.cabal
  - packunused
  - hlint --cpp-define HLINT src

notifications:
  irc:
    channels:
      - "irc.freenode.org#ermine"
    skip_join: true
    template:
      - "\x0313ermine\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
